### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [2]:
import numpy as np

vector = np.random.rand(10)

print("Vector:", vector)
print("Vector shape:", vector.shape)


Vector: [0.68764961 0.94874225 0.83352305 0.03239251 0.79065216 0.78613146
 0.68253533 0.13049149 0.39807417 0.78604376]
Vector shape: (10,)


In [3]:
matrix = np.array([
    [11, 14, 17],
    [20, 23, 26],
    [29, 32, 35]
])

print("Matrix:")
print(matrix)
print("Matrix shape:", matrix.shape)


Matrix:
[[11 14 17]
 [20 23 26]
 [29 32 35]]
Matrix shape: (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [4]:
vector = np.random.rand(10)

matrix = np.array([
    [11, 14, 17],
    [20, 23, 26],
    [29, 32, 35]
])


In [5]:
vector_plus_10 = np.round(vector + 10, 2)

print("Vector + 10 (rounded):", vector_plus_10)


Vector + 10 (rounded): [10.75 10.11 10.77 10.7  10.28 10.89 10.38 10.9  10.74 10.68]


In [6]:
matrix_times_2 = matrix * 2

print("Matrix * 2:")
print(matrix_times_2)


Matrix * 2:
[[22 28 34]
 [40 46 52]
 [58 64 70]]


In [7]:
vector_squared = vector ** 2

print("Vector squared:", vector_squared)


Vector squared: [0.56102459 0.01192889 0.58722218 0.48536198 0.07688175 0.78755222
 0.14386653 0.81463991 0.543878   0.46555491]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [8]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [9]:
result_matrix = np.dot(A, B)

print("A · B =")
print(result_matrix)
print("Розмірність:", result_matrix.shape)


A · B =
[[0.232  0.1627 0.2145]
 [0.3061 0.4867 0.633 ]
 [0.1393 0.2261 0.294 ]]
Розмірність: (3, 3)



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [12]:
vector = np.array([0.18, 0.53, 0.75, 0.47, 0.35, 0.21, 0.17, 0.58, 0.75, 0.38])

A = np.array([
    [0.18, 0.53],
    [0.75, 0.47],
    [0.35, 0.21]
])
B = np.array([
    [0.17, 0.58, 0.75],
    [0.38, 0.11, 0.15]
])

result_matrix = np.dot(A, B)  # 3x3
print("result_matrix:\n", result_matrix)
print("Shape:", result_matrix.shape)

result_matrix_T = result_matrix.T
print("\nTransposed result_matrix:\n", result_matrix_T)
print("Shape:", result_matrix_T.shape)

vector_T = vector.T
print("\nOriginal vector:\n", vector)
print("Shape:", vector.shape)
print("Transposed vector (1D):\n", vector_T)
print("Shape:", vector_T.shape)

column_vector = np.expand_dims(vector, axis=1)
print("\nColumn vector:\n", column_vector)
print("Shape:", column_vector.shape)

column_vector_T = column_vector.T
print("\nTransposed column_vector:\n", column_vector_T)
print("Shape:", column_vector_T.shape)


result_matrix:
 [[0.232  0.1627 0.2145]
 [0.3061 0.4867 0.633 ]
 [0.1393 0.2261 0.294 ]]
Shape: (3, 3)

Transposed result_matrix:
 [[0.232  0.3061 0.1393]
 [0.1627 0.4867 0.2261]
 [0.2145 0.633  0.294 ]]
Shape: (3, 3)

Original vector:
 [0.18 0.53 0.75 0.47 0.35 0.21 0.17 0.58 0.75 0.38]
Shape: (10,)
Transposed vector (1D):
 [0.18 0.53 0.75 0.47 0.35 0.21 0.17 0.58 0.75 0.38]
Shape: (10,)

Column vector:
 [[0.18]
 [0.53]
 [0.75]
 [0.47]
 [0.35]
 [0.21]
 [0.17]
 [0.58]
 [0.75]
 [0.38]]
Shape: (10, 1)

Transposed column_vector:
 [[0.18 0.53 0.75 0.47 0.35 0.21 0.17 0.58 0.75 0.38]]
Shape: (1, 10)
